#  Tema 2 

#### Termen de predare: 18 octombrie 2022, ora 20:00.

### Precizări

1. Se vor folosi **type annotations** pentru variabile, parametri tuturor funcțiilor, tipuri de retur. Se vor folosi **docstrings** pentru toate funcțiile. Neîndeplinirea acestei cerințe duce la înjumătățirea punctajului pentru exercițiul în cauză. 
1. Înainte de a trimite tema, verificați acoperirea cerințelor. 


### Conținut

1. Exercitii cu functii
1. Exercitii cu NumPy

## Execiții cu funcții:


 (1p) 1. Să se scrie o funcție care primește ca parametru un număr de 5 cifre. Să se returneze o listă cu toate numerele prime formate din cifrele parametrului.

In [25]:
from typing import List

def primeCheck(n:list) -> bool:
    """
    A bool function in which I check whether a 
    number (recieved as string and converted to int)
    is prime or not.
    """
    n=int(n)
    if n==1 or n==0 or (n % 2 == 0 and n > 2):
        return False
    else:
        for i in range(3, int(n**(1/2))+1, 2):
            if n%i == 0:
                return False
        return True

def getPermutari(lst:list) -> list:
    """
    A function that prints all the permutations of a 
    given list. If there is one element, one permutation is possible.
    It returns a list.
    """
    if len(lst) == 0:
        return []
    if len(lst) == 1:
        return [lst]
    l = []
    for i in range(len(lst)):
        m=lst[i]
        restLst = lst[:i] + lst[i+1:]
        for j in getPermutari(restLst):
            l.append([m] + j)
    return l

numar:str = '12563'
prime:List[str] = []
lstNr1:list = list(numar)
ok = 0
for k in getPermutari(lstNr1):
    a  = ''.join(k)
    if(primeCheck(a) == True):
        ok = 1
        print(a)
if ok == 0:
    print("Nu sunt numere prime.")
# help(primeCheck)
# help(getPermutari)


12653
15263
16253
21563
25163
26153
26513
23561
51263
52163
52631
52361
56123
61253
62351
65123
65213
63521
32561
36251


(1p) 2. Scrieți o funcție care primește ca parametru o frază de maxim 12 cuvinte și care returnează un tuplu ce conține doar cuvintele palindroame. Un palindrom este un șir de caractere care citit de la dreapta la stânga are același continut ca si citirea de la stanga la dreapta.

In [51]:
import string 

def este_palindrom(s:str) -> bool:
    """
    A bool function that will check if a string is palindrom or not. 
    """
    val = set(string.ascii_letters)
    raspuns_s = ''.join(ch for ch in s if ch in val)
    cf_s = raspuns_s.casefold()
    return cf_s == cf_s[::-1]

def tuplePal(x:list) ->tuple:
    """
    Function that will check every word of the sentence
    and if it's a palindrom it will put it in a list; 
    a list that will be converted to a tuple.
    This function returns a tuple 
    """
    for i in range(len(x)):
        if(este_palindrom(x[i])):
            listaFinala.append(x[i])
    tuple1:tuple = (*listaFinala,)
    print(tuple1)

s:str = "ELE FAC CAFELE SIS TERMIN AZI YOY ELEFACCAFELE"
listaFinala:list =[]
a:list = s.split(" ")
x:list = [str(i) for i in a]
tuplePal(x)

('ELE', 'SIS', 'YOY', 'ELEFACCAFELE')


(1p) 3. Definiți o funcție care primește ca parametru o propoziție (string sau listă). Să se returneze un tuplu ce indică numărul de consoane, numărul de vocale și numărul de cifre din parametrul primit. Verificați dacă suma celor 3 valori formează un pătrat perfect.

In [25]:
import string
import math

from numpy import double

def formeazaPatrat(tpl:tuple) -> str:
    """
    This function receives the tuple and checks if the sum
    of those numbers is a perfect square or not. 
    """
    suma:int = tpl[1] + tpl[3] + tpl[5]
    radacina:double = math.sqrt(suma)
    if int(radacina + 0.5) **2 == suma:
        print (suma, " este patrat perfect.")
    else:
        print (suma, " nu este patrat perfect.")


def numarCaractere(lista:list) -> tuple:
    """
    A function that check how many vowels, consonants and numbers
    a sentance has; Receives a list and returns a tuple. 
    """
    vowels:str = "aeiou"
    consonants:str = "bcdfgjklmnpqstvxz"
    numbers:str = "1234567890"
    nrVowels:int = 0
    nrConsonants:int = 0
    nrNumbers:int = 0
    nmbrs:list = []
    for word in lista:
        stri:str = word
        ct=0
        for letter in word:
            if(stri[ct] in vowels):
                nrVowels = nrVowels + 1
            if(stri[ct] in consonants):
                nrConsonants = nrConsonants + 1
            if(stri[ct] in numbers):
                nrNumbers = nrNumbers + 1
            ct = ct + 1
    nmbrs.append('Numar vocale: ')
    nmbrs.append(nrVowels)
    nmbrs.append('Numar consoane: ')
    nmbrs.append(nrConsonants)
    nmbrs.append('Numar numere: ')
    nmbrs.append(nrNumbers)
    tuple1:tuple = (*nmbrs,)
    return tuple1

sentence:str = "1 cuuii ppe 1 ccui see ssscoate"
lista:list = sentence.split(" ")
tpl:tuple = numarCaractere(lista)
print(tpl)
formeazaPatrat(tpl)

# vowels = 12
# consonants = 11
# numbers = 2
# formeazaPatrat = da/nu

('Numar vocale: ', 12, 'Numar consoane: ', 11, 'Numar numere: ', 2)
25  este patrat perfect.


(1p) 4. Să se scrie o funcție recursivă care determină dacă un număr se poate descompune în sumă de numere consecutive.

In [26]:
def esteSumaNrConsecutive(numar:int) -> bool:
    """
    If the number can be put as a sum of consecutive
    numbers the function will return true. We go by the rule that if a
    number is a power of 2, then it's true
    """
    return ((numar&(numar-1))and numar)

numar:int = 10
if(esteSumaNrConsecutive(numar)):
    print("Se poate descompune")
else:
    print("Nu se poate descompune")

# exemple: 10 -> True (1+2+3+4); 5 -> True (2+3); 16 -> False

Se poate descompune


## Probleme NumPy

(0.5 p) 1. Se dă un vector NumPy. Să se determine lista elementelor unice. Formați o matrice pătratică de dimensiune  `len(v)/2` care să conțină elementele unice din vector.
Completați cu cmmdc al elementelor unice pozițiile din matrice rămase libere.  

In [102]:
import numpy as np

def cmmdc(m:any,n:any) -> int:
    """
    Functie ce imi returneaza cmmdc-ul a doua numere; 
    Returneaza un int.
    """
    while n!=0:
        rest=m%n
        m=n
        n=rest
    return m

lista:list = [5, 6, 7, 7, 8, 9, 5]
vector:np.ndarray = np.array(lista)
vectorUnic:np.ndarray = np.unique(vector)
dim:int = int(len(vector)/2)
print(vectorUnic)
lista = vectorUnic.tolist()
div = cmmdc(lista[0],lista[1])
while(len(lista) != dim*dim):
    lista.append(div)
vectorUnic = np.array(lista)
print(vectorUnic)
mat = vectorUnic.reshape(dim,dim)
print(mat)

[5 6 7 8 9]
[5 6 7 8 9 1 1 1 1]
[[5 6 7]
 [8 9 1]
 [1 1 1]]


(1.5 p) 2. Se dau punctele de forma `An(5n, 8n+1)`. 

a) Verificați dacă punctele `An-1`, `An`,`An+1` formează un triunghi. <br>
b) Verificați dacă punctele `A1`,`A2`,`An` sunt coliniare. <br>
c) Scrieți ecuația dreptei `A1A2`.
    
   **Indicație**: Puteți folosi noțiunea de determinant.

In [39]:
import numpy as np

def checkTriangleAndCollinear(p1:tuple,p2:tuple,p3:tuple) -> None:
    """
    This function checks if 3 given point can form a 
    triangle or not. It prints the specific message
    """
    a = (p1[0] * (p2[1]-p3[1]) + p2[0] * (p3[1] - p1[1]) + p3[0] * (p1[1] - p2[1]))
    if a==0:
        print("Nu formeaza triunghi, dar sunt coliniare")
    else:
        print("Formeaza triunghi, si nu sunt coliniare")

def ecuatiaDreptei(mat):
    """
    Functie care o sa imi calculeze ecuatia dreptei a doua linii
    """
    x1 = mat[0][0]
    y1 = mat[0][1]
    x2 = mat[1][0]
    y2 = mat[1][1]
    a= y2 - y1
    b= x1 - x2
    c = a * (x1) + b * (y1)
    if(b<0):
        print(a,"x +", b, "y =", c, "\n")
    else:
        print(a,"x +", b, "y =", c, "\n")

p1:tuple = (5,9)
p2:tuple = (10,17)
p3:tuple = (15, 25)
poi:tuple = (p1,p2,p3)

checkTriangleAndCollinear(p1,p2,p3)
mat:np.array= np.asarray(poi)
print (mat)
ecuatiaDreptei(mat)

Nu formeaza triunghi, dar sunt coliniare
[[ 5  9]
 [10 17]
 [15 25]]
8 x + -5 y = -5 



(1p) 3. Pentru o matrice de numere să se determine suma dintre minimul si maximul elementelor de pe linii sau de pe coloane, în funcție de valoarea unui parametru de tip boolean `compute_on_columns`.

In [75]:
import numpy as np

def compute_on_columns(a):
    """
    O functie care primeste ca parametru valoarea 1 sau 0 si
    in functie de aceasta calculeaza minimile si maximele 
    de pe linii/coloane.
    1 este pentru linii
    0 este pentru coloane
    """
    if a == 1:
        minim:np.array = np.amin(mat, axis = a)
        maxim:np.array = np.amax(mat, axis = a)
    elif a==0:
        minim:np.array = np.amin(mat, axis = a)
        maxim:np.array = np.amax(mat, axis = a)
    suma:np.array = minim + maxim
    print(minim)
    print(maxim)
    print(suma)


mat:np.array = np.array([[1,2,40], [4,11,80], [9,7,8]])
compute_on_columns(1)
print("\n")
compute_on_columns(0)

[1 4 7]
[40 80  9]
[41 84 16]


[1 2 8]
[ 9 11 80]
[10 13 88]


(1p) 4. Pentru un număr introdus de la tastaură, generați o matrice pătratică cu elemente aleatorii din intervalul `[0,2n]`. Calculați minimul elementelor de pe 
diagonala principală a matricei și maximul elementelor de pe diagonala secundară a matricei. Returnați rezultatele sub forma de tuplu.

(2p) 5. Descarcați setul de date Wine descris la 'http://archive.ics.uci.edu/ml/datasets/Wine', fișierul `wine.data`, și încărcați-l într-o matrice NumPy, 
folosind `np.genfromtxt`. Alegeți aleator 28 de poziții din cadrul matricei de valori, setați pe aceste pozitii `NaN`.  Construiți o funcție care, 
primind la intrare o matrice, returnează o colecție cu indicii de linii respectiv de coloane în care se găsesc valori `NaN`, precum si matricea 'corectată':  valorile `NaN` se umplu cu o valoare ca parametru al funcției. 