# Laborator 3 - tema 3

* **Termen de predare: 26 octombrie 2022, ora 20:00**

Se vor folosi type annotations pentru variabile, parametrii tuturor funcțiilor, tipuri de retur. Se vor folosi docstrings pentru toate funcțiile. Neîndeplinirea acestei cerințe duce la înjumătățirea punctajului pentru exercițiul în cauză.  

Se acordă doua puncte din oficiu. Fișierul va fi denumit tema3_ia_nume_prenume.ipynb. Verificați înainte de trimitere faptul ca execuția celulelor de sus în jos funcționează corespunzător. Aserțiunile sunt obligatoriu a fi indeplinite. Suplimentar, puteti face verificari si pentru alte valori.

1. (1p) Pentru un vector de numere, care sunt toate pozitiile pe care apare valoarea minima?
Folositi functii NumPy.

In [1]:
import numpy as np
v:np.array = np.array([1, 2, 3, 4, 4, 3, 1] * 2, dtype=np.float32) 
# v = [1, 2, 3, 4, 4, 3, 1, 1, 2, 3, 4, 4, 3, 1]
mini:int = np.amin(v) 
positions:list = []
for i in range(len(v)):
    if (v[i] == mini):
        positions.append(i)
positions_min:np.array = np.array(positions)
print(positions_min)
assert np.all(positions_min == [ 0,  6,  7, 13])

[ 0  6  7 13]


2. (1p) Construiti o functie care, primind o matrice, determina pe ce pozitii (linii, coloane) se afla valorile in intervalele [a, b] sau [c, d] date ca parametri. Functia va returna un tuplu de doi vectori: primul e cu indicii de linie, al doilea cu indicii de coloana unde se afla elementele cautate.

Exemplu:

In [2]:
import numpy as np
from numpy import array

# de adaugat typing annotations pentru parametri si tip de retur
def pos_values(mat:np.ndarray,a:int,b:int,c:int,d:int) ->tuple:
    """
    Functie care imi parcurge elementele matricei, le verifica daca sunt
    egale cu numerele din intervalele date ca parametri, daca da
    mi le adauga la un vector.
    Imi returneaza un tuple
    """
    rows:array = []
    cols:array = []
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            for k in range(a,b+1):
                 if(mat[i][j]==k):
                    rows.append(i)
                    cols.append(j)
            for l in range(c,d+1):
                 if(mat[i][j]==l):
                    rows.append(i)
                    cols.append(j)
    rows = tuple(rows)
    cols = tuple(cols)
    return rows, cols

mat:np.ndarray = np.arange(12).reshape(3, 4)
rows, cols = array(pos_values(mat, 2, 4, 6, 8))
print(rows)
print(cols)
assert np.all(rows == [0, 0, 1, 1, 1, 2])
assert np.all(cols == [2, 3, 0, 2, 3, 0])

mat:np.ndarray = -np.arange(12).reshape(3, 4)
rows, cols = array(pos_values(mat, 2, 4, 6, 8))
print(rows)
print(cols)
assert np.all(rows == [])
assert np.all(cols == [])

[0 0 1 1 1 2]
[2 3 0 2 3 0]
[]
[]


3. (1p) Se da un vector cu numere intregi nenule. Sa se determine toti indicii `i` unde urmeaza o schimbare de semn. Codul se va scrie intr-o functie adnotata.

Exemplu: 
```python
v = [1, 2, -1, 2, 3, -1, 3, -10, -10, -10]
```
Trebuie sa rezulte vectorul de indici: `[1, 2, 4, 5, 6]`.

De luat in considerare ca:
1. Magnitudinea valorilor nu conteaza, doar semnele lor
1. Functia `where` gaseste indicii unde anumite proprietati sunt indeplinite

In [3]:
from turtle import pos
import numpy as np

def jumping(v:np.ndarray) -> list:  # de adnotat, doctstring
    """
    Determina toti indici i pentru care urmeaza o schimbare de semn  .
    Returneaza lista cu indicii; primeste ca parametru un array
    """
    assert np.all( v != 0), 'All values should be non-zero'
    indexi:list = []
    for i in range(len(v)-1):
        if v[i] * v[i+1] < 0:
            indexi.append(i)
    return indexi

# test 1
v:np.ndarray = np.array([1, 2, -1, 2, 3, -1, 3, -10, -10, -10])
assert np.all(jumping(v) == [1, 2, 4, 5, 6]) 

# test 2: random vector, naive counting
v = np.random.randint(-100, 100, 1000)
# patching 0 values
v[v==0] = -1
# naive way of counting jumps:
positions = []
for i in range(len(v)-1):
    if v[i] * v[i+1] < 0:
        positions.append(i)
assert np.all(positions == jumping(v))

4. (1p) Generati o matrice aleatoare de dimensiune m*n care are m valori nan (not-an-number, https://numpy.org/doc/stable/reference/constants.html), la pozitii aleatoare. Determinati apoi suma elementelor non-nan din matrice in doua feluri (construiti doua functii). Comparati sumele returnate.

Exemplu:
```python
a = get_matrix(3, 4)
# sa presupunem ca a este
a = 
    1.5 2.2 np.nan
    4.3 np.nan np.nan
    10.1 5.0 -3.1
```

Suma elementelor este 20.0.
Indicatii: folositi functia `np.random.choice` cu parametri adecvati pentru a alege indici in mod aleator, fara repetare. 

In [4]:
from cmath import isnan
import numpy as np
from numpy import ravel


def get_matrix(m:int, n:int) -> np.ndarray:  # de adnotat, docstring
    """
    Creaza matricea aleatorie de simensiuni m,n care are m 
    valori nan plasate random.
    """
    a:np.ndarray = np.random.randint(-100, 100, size = (m,n))
    a = a * 0.1
    mat:np.ndarray = np.random.choice(a.size, m, replace=False)
    a.ravel()[mat] = np.nan
    assert np.sum(np.isnan(a)) == m  # verificare: avem exact m nan-uri
    return a

def sum_1(a:np.ndarray) -> float:  # de adnotat, docstring
    """
    Prima metoda de a afla suma valorilor non-nan cu ajutorul functiei
    nansums(); Elementele nan o sa fie tratate ca 0. 
    """
    return np.nansum(a)

def sum_2(a:np.ndarray) -> float: # de adnotat, docstring
    """
    Metoda care parcurge fiecare element in parte, Daca este nan
    adunam cu 0, altfel adunam elementul la suma
    """
    s = 0
    m, n = a.shape
    for i in range(m):
        for j in range(n):
            if(np.isnan(a[i, j])):
                s=s+0
            else:
                s=s+a[i, j]
    return s

def naive_sum(a: np.ndarray) -> float:
    s = 0
    m, n = a.shape
    for i in range(m):
        for j in range(n):
            s += a[i, j] if not np.isnan(a[i, j]) else 0
    return s

m, n = 3, 4
a:np.ndarray = get_matrix(m, n)

assert np.allclose(sum_1(a), naive_sum(a))
assert np.allclose(sum_2(a), naive_sum(a))

# pentru studenti: de ce e nevoie de allclose si nu se face comparatie cu == ?

5. (1p) Folosnd functia `np.convolve`, sa se determine media alunecatoare (moving average) pentru un vector de 10000 de numere aleatoare; lungimea ferestrei alunecatore se da ca parametru al functiei construite de voi. Comparati rezultatele si viteza de executie cu a functiaie `naive_moving_average`.

Referinte:
1. [Moving average](https://en.wikipedia.org/wiki/Moving_average)
1. [np.convolve: How to Use Numpy convolve() Method](https://appdividend.com/2022/10/14/np-convolve/)

In [5]:
import numpy as np

def moving_average_fast(x:np.ndarray, w:int) -> np.ndarray:  # de adnotat, docstring
    """
    Metoda care calculeaza media alunecatoare cu ajutorul functiei
    np.convolve. Returneaza un array. Primeste ca parametri
    un array si un int.
    """
    assert x.ndim == 1, 'One dimension numpy array'
    assert w > 1, 'Average of at least two values'
    rez:np.ndarray = np.convolve(x,np.ones(w)/w, mode='valid')
    return rez

def moving_average_slow(x:np.ndarray, w:int) -> np.ndarray: # de adnotat, docstring
    """
    Metoda de calcularea pentru media alunecatoare. Primeste
    un array si un int ca parametru; returneaza un array/
    """
    assert x.ndim == 1, 'One dimension numpy array'
    assert w > 1, 'Average of at least two values'
    result:np.ndarray = np.zeros(x.shape[0]-w+1)
    for i in range(x.shape[0]-w+1):
        result[i] = np.mean(x[i:i+w])
    return result

len_vec, w = 10000, 10
x:np.ndarray = np.random.rand(len_vec)

a:np.ndarray = moving_average_fast(x, w)
b:np.ndarray = moving_average_slow(x, w)
assert len(a) == len(b), 'The two methods should return vectors of the same lengths'
assert np.allclose(a, b), 'The two methods should return close vectors'

%timeit moving_average_fast(x, w)
%timeit moving_average_slow(x, w)

103 µs ± 4.77 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
212 ms ± 4.76 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


6. (1p) Se dau vectorii de valori $x=[x_0 \dots x_{n-1}]$, $t=[t_0, \dots t_n-1]$, cu $t[0] < t[1] < \dots$. Sa se calculeze intr-o maniera vectorizata vectorul $v$ ale carui componente sunt:
$$
v[i] = \frac{x[i+1] - x[i]}{t[i+1] - t[i]}
$$

In prealabil sa se verifice (vectorizat sau functii NumPy) ca vectorul $t$ este format doar din valori strict crescatoare. Comparati rezultatele si viteza de executie cu o implementare care construieste vectorul $v$ pas cu pas.

Optional: incercati si o implementare folosind Numba. 

In [6]:
import numpy as np

n = 100000
x = np.random.rand(n)
t = np.random.randint(1, 10, n)
t = t.cumsum()

def is_increasing(t:np.ndarray) -> bool: # de adnotat, docstring
    """
    Metoda care parcurge toate elementele lui t si
    verifica daca cresc; 
    Primeste un array si returneaza un bool.
    """
    for i in range(len(t)-1):
        if t[i]>t[i+1]:
            return False
    return True
assert is_increasing(t), 't should be an increasing vector'

def fast_v(x:np.ndarray, t:np.ndarray) -> np.ndarray: # de adnotat, docstring
    """
    Metoda care calculeaza vectorul v cu elementele
    (x[i+1]-x[i])/(t[i+1]/t[i]), facand mai intai
    scaderile dupa care impartirea intre ele 
    adaugand-o direct la v. Primeste ca parametru 
    doi vectori; returneaza tot un vector.
    """
    assert is_increasing(t), 'non increasing values'
    i=0
    while i in x:
        a=np.subtract(x[i+1],x[i])
        b=np.subtract(t[i+1],t[i])
        np.append(v, a/b)
        i=i+1
    return v

def slow_v(x:np.ndarray, t:np.ndarray) -> np.ndarray: # de adnotat, docstring
    """
    Metoda care calculeaza vectorul v cu elementele
    (x[i+1]-x[i])/(t[i+1]/t[i]), adaugand calculul
    direct la v, fara sa facem operatii in alte variabile. 
    Primeste ca parametru doi vectori; returneaza tot un vector.
    """
    assert is_increasing(t), 'non increasing values'
    i=0
    while i in x:
        np.append(v, (x[i+1]-x[i])/(t[i+1]/t[i]))
        i=i+1
    return v

v1:np.ndarray = fast_v(x, t)
v2:np.ndarray = slow_v(x, t)

assert v1.shape == v2.shape
assert np.allclose(v1, v2)

%timeit fast_v(x, t)
%timeit slow_v(x, t)

55.3 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
57.4 ms ± 4.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


7. (2p) Se da o matrice $a$ cu numere reale. 
    1. Sa se calculeze o alta matrice $b$ care are valorile calculate astfel:
    $$
    b[i, j] = \frac{a[i, j] - MIN}{MAX-MIN}
    $$
    unde $MAX$ si $MIN$ sunt valoarile minima, respectiv maxima din $a$. Tranformarea se face printr-o functie care preia o matrice si returneaza un tuplu compus din matricea $b$ si valorile $MIN$ si $MAX$ 
    2. Verificati ca in urma acestei transformari matricea $b$ are valorile in intervalul $(-epsilon, 1+epsilon)$, unde $epsilon=1e-5$.
    3. Daca se dau $b$, $MIN$, $MAX$, care este transfomarea inversa prin care obtinem matricea $a$ originara? Verificati ca valorile lui $a$ si $a_{reconstituit}$ sunt aproximativ egale. 

In [7]:
from typing import Tuple
import numpy as np

m, n = 100, 200
eps = 1e-5
a = np.random.randn(m, n)

# rezolvare pct A
def min_max_scale(x:np.ndarray) -> tuple: # de adnotat, docstring
    mini = np.min(x)
    maxi = np.max(x)
    b:list=[]
    for i in range(m):
        col = []
        for j in range(n):
            col.append((x[i,j]-mini)/(maxi-mini))
        b.append(col)
    return b, mini, maxi

# rezolvare pct B
def check_scaling(y: np.ndarray, eps = 1e-5) -> bool: # de adnotat, docstring
    """
    Verifica daca numere din matricea b sunt cuprinse intre
    -epsilon si epsilon+1. Primeste un array si returneaza bool.
    """
    assert eps > 0
    ok=1
    nEps = np.negative(eps)
    for i in range(m):
        for j in range(n):
            a = y[i][j]
            if (a < nEps or a > eps+1):
                ok=0
    if ok == 1:
        return True
    else:
        return False

assert check_scaling(min_max_scale(a)[0])

# # rezolvare pct C
# def inverse_min_max_scale(y: np.ndarray, MIN: float, MAX: float) # de adnotat, docstring
#     assert MAX > MIN
#     return ...

b, MIN, MAX = min_max_scale(a)

# assert np.allclose(a, inverse_min_max_scale(b, MIN, MAX))